### ISSUE TITLE
Sweetalert?

### ISSUE THREAD

**Issue by javathunderman** [HashAway/TicketSys#1]
https://github.com/t4t5/sweetalert

If you want to use it, have fun. 

@Taloz

**Comment by Taloz** [comment]
I think Bootstrap [modals](http://getbootstrap.com/javascript/#modals) or [alerts](http://getbootstrap.com/javascript/#alerts) should work fine for this project.

**Comment by javathunderman** [comment]
We could have a lot more freedom with Sweetalert. Are you sure?

**Comment by javathunderman** [comment]
Guess you are then.
